project:
  type: website
  output-dir: docs

website:
  title: "JIA"
  site-url: "https://jiazhang42.github.io/mysite/"
  navbar:
    pinned: true
    background: "#455D3E"
    left:
      - research.qmd
      - teaching.qmd
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
      - href: cv/jia_cv.pdf
        text: CV
      - href: google2f8aad75c360b5d9.html
        text: .

      
  favicon: "/images/favicon.png"
      
  page-footer:
    left: "Content {{< fa brands creative-commons >}} {{< var page.copyright_year >}} by [{{< var name >}}]({{< var url >}})"
    right: |
      Made with {{< fa heart >}} and [Quarto](https://quarto.org/)<br>
      [View source code at {{< fa brands github >}} GitHub]({{< var github >}})

format:
  html:
    theme: 
      - united
      - styles.scss
    toc: true
    highlight-style: monokai



